version: '3'
services:
  react-ec2-github-actions:
    container_name: react-ec2-github-actions
    build:
      context: ./react-ec2-github-actions
      dockerfile: Dockerfile
    volumes:
      - react-ec2-github-actions:/react-ec2-github-actions/build/  # build files will be added at this directory !!!

  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - react-ec2-github-actions:/usr/share/nginx/html/react-ec2-github-actions # Copy React App's build files to the Nginx directory

volumes:
  react-ec2-github-actions: